# Generated by Django 2.0.7 on 2019-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
