# Generated by Django 2.0.7 on 2019-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingClub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='typeOfEvent',
            field=models.CharField(choices=[('Upcoming Event', 'Upcoming Event'), ('Past Event', 'Past Event')], default='Upcoming Event', max_length=20),
            preserve_default=False,
        ),
    ]
