# Generated by Django 2.0.7 on 2019-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingClub', '0003_auto_20190203_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='typeOfEvent',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Past', 'Past')], default='Upcoming', max_length=20),
        ),
    ]
